{% set name = "cubo" %}
{% set version = "2024.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cubo-{{ version }}.tar.gz
  sha256: d93dedcfa8b2fa123357236050653017b3dce4e14ab6e0d2c069cbebffef2eb1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - dask-core >=2023.7.0
    - numpy <2.0.0
    - pandas >=2.0.3
    - planetary-computer >=1.0.0
    - pystac-client >=0.7.2
    - scipy >=1.12.0
    - stackstac >=0.4.4
    - xarray >=2023.6.0

test:
  imports:
    - cubo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ESDS-Leipzig/cubo
  summary: On-Demand Earth System Data Cubes in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://cubo.readthedocs.io/en/latest/
  dev_url: https://github.com/ESDS-Leipzig/cubo

extra:
  recipe-maintainers:
    - davemlz
